ui_register
ThanhLuan2010/Om_healing pull request #2
Opened 2023-05-17 08:24 UTC by LeHongPhatt

2023-05-17 11:59 UTC, ThanhLuan2010 requested changes

2023-05-17 11:59 UTC, ThanhLuan2010 commented on src/screens/RegisterScreen/index.js
> +      style={{ flex: 1 }}
bỏ style inline đi

2023-05-17 11:59 UTC, ThanhLuan2010 commented on src/screens/RegisterScreen/index.js
> +                colors={["#521717FA", "#8F1515"]}
color bỏ vào mục theme.color

2023-05-17 11:59 UTC, ThanhLuan2010 commented on src/screens/RegisterScreen/index.js
> +    // height: 200,
xoá cmt

2023-05-18 02:18 UTC, LeHongPhatt commented on src/screens/RegisterScreen/index.js
> +                colors={["#521717FA", "#8F1515"]}
xong

2023-05-18 02:18 UTC, LeHongPhatt commented on src/screens/RegisterScreen/index.js
> +    // height: 200,
xong

2023-05-18 04:01 UTC, merged